theme: minima
title: "ReLU Neural ODE Density Flow Simulator"
description: "Interactive web-based simulator for visualizing probability density evolution under single-neuron ReLU neural ODEs"
author: "Antonio Alvarez"
github_username: antonioalvarezl

# Build settings
markdown: kramdown
highlighter: rouge

# GitHub Pages settings
plugins:
  - jekyll-feed
  - jekyll-sitemap

# SEO and social
twitter:
  card: summary_large_image
  creator: "@antonioalvarezl"

# Repository settings  
repository: antonioalvarezl/relu-flow-simulator
url: "https://antonioalvarezl.github.io"
baseurl: "/relu-flow-simulator"

# Navigation
header_pages:
  - index.html
  - DOCUMENTATION.md

# Collections
collections:
  docs:
    output: true
    permalink: /:collection/:name/